(()=>{'use strict';
const D=window.PUBLIC_SITE_DATA||{headers:[],records:[]};const HEADERS=D.headers||[],COLS=D.cols||[],ROWS=D.records||[];const idx=Object.fromEntries(HEADERS.map((h,i)=>[h,i]));const rowNoIndex=HEADERS.length;
const H={site:'현장명',sn:'S/N',grade:'보고서 등급',region:'지역',old:'계약명 (명칭 변경 전)',planS:'현장점검 계획 > 시작',planE:'현장점검 계획 > 종료',inspEnd:'현장점검 종료',reportDone:'문서작성 진행 현황 > 보고서 작성 완료',reportStatus:'문서작성 진행 현황 > 현황',docMonth:'문서작성 > 진행월',bindIn:'문서작성 > 제본 입고'};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const val=(r,h)=>idx[h]===undefined?'':r[idx[h]];const has=v=>v!==null&&v!==undefined&&String(v).trim()!=='';const isDate=v=>/^\d{4}-\d{2}-\d{2}/.test(String(v||''));const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const nval=v=>{if(typeof v==='number')return Number.isFinite(v)?v:null;const n=Number(String(v??'').replace(/,/g,'').trim());return Number.isFinite(n)?n:null};
function fmt(h,v){if(!has(v))return '-';const n=nval(v);if(h==='연면적(m2)'&&n!==null)return n.toLocaleString('ko-KR',{maximumFractionDigits:2})+' m²';if(h==='세대수'&&n!==null)return Math.round(n).toLocaleString('ko-KR')+' 세대';if(/수량 >/.test(h)&&n!==null)return n.toLocaleString('ko-KR');return String(v)}
function calc(r){const reportDoneDate=isDate(val(r,H.reportDone));const planned=isDate(val(r,H.planS))||isDate(val(r,H.planE));const inspectionDone=isDate(val(r,H.inspEnd));const bindIn=isDate(val(r,H.bindIn));const overall=!bindIn;const reportWork=!reportDoneDate&&(has(val(r,H.reportStatus))||has(val(r,H.docMonth))||inspectionDone);return{bindIn,reportDoneDate,planned,inspectionDone,reportWork,overall,target:overall&&!planned&&!inspectionDone,inspecting:overall&&planned&&!inspectionDone,inspected:overall&&inspectionDone,reportMissing:overall&&!reportDoneDate}}
function stage(kind,state){const map={done:['완료','done'],doing:['진행 중','doing'],wait:['대기','wait'],target:['점검대상','wait'],missing:['미작성','wait']};const [txt,cl]=map[state];return `<div class="stage ${cl}"><strong>${kind}</strong><small>${txt}</small></div>`}
const FIELD_STORE='public_site_search_display_fields_v1';const RECOMMENDED=['지역','보고서 등급','점검 단계','현장점검 계획 > 시작','현장점검 종료','문서작성 진행 현황 > 보고서 작성 완료','점검 구분 (유지) : 업무지원'];let displayFields=JSON.parse(localStorage.getItem(FIELD_STORE)||'null')||RECOMMENDED.filter(h=>idx[h]!==undefined);let activeFilter='registered',visible=100,selected=null,currentTab='basic';
const searchIndex=ROWS.map(r=>[val(r,H.site),val(r,H.old),val(r,H.region),val(r,H.sn),val(r,H.grade)].map(v=>String(v||'').toLowerCase()).join(' '));
function selectedDataHtml(r){const fs=displayFields.filter(h=>h!==H.site&&idx[h]!==undefined);if(!fs.length)return'';return `<div class="selectedData">${fs.map(h=>`<div class="dataitem"><span class="dk">${esc(h)}</span><span class="dv">${esc(fmt(h,val(r,h)))}</span></div>`).join('')}</div>`}
function card(r){const s=calc(r);const planState=s.inspectionDone?'done':(s.planned?'doing':'target');const inspectState=s.inspectionDone?'done':(s.planned?'doing':'wait');const reportState=s.reportDoneDate?'done':(s.reportWork?'doing':'missing');const key=r[rowNoIndex];return `<article class="card"><div class="cardtop"><div class="site">${esc(val(r,H.site)||'(현장명 없음)')}</div><div class="sn">${esc(val(r,H.sn)||'')}</div></div><div class="flow">${stage('점검계획',planState)}<div class="arrow">›</div>${stage('현장점검',inspectState)}<div class="arrow">›</div>${stage('보고서',reportState)}</div>${selectedDataHtml(r)}<div class="cardfoot"><button class="detailBtn" data-row="${key}">상세 조회</button></div></article>`}
function filtered(){const q=$('#search').value.trim().toLowerCase();let a=ROWS.map((r,i)=>[r,i]).filter(([r,i])=>!q||searchIndex[i].includes(q)).map(x=>x[0]);a=a.filter(r=>{const s=calc(r);return activeFilter==='registered'?true:activeFilter==='all'?s.overall:activeFilter==='target'?s.target:activeFilter==='inspecting'?s.inspecting:activeFilter==='inspected'?s.inspected:activeFilter==='reportMissing'?s.reportMissing:activeFilter==='reportDone'?(s.overall&&s.reportDoneDate):true});a.sort((a,b)=>{const sa=calc(a).bindIn?1:0,sb=calc(b).bindIn?1:0;return sa-sb||Number(b[rowNoIndex]||0)-Number(a[rowNoIndex]||0)});return a}
function render(){const a=filtered(),shown=a.slice(0,visible);$('#resultCount').textContent=`${a.length.toLocaleString()}건`;$('#cards').innerHTML=shown.length?shown.map(card).join(''):'<div class="empty">검색 조건에 맞는 현장이 없습니다.</div>';$('#moreResults').innerHTML=a.length>shown.length?`<button id="moreBtn">100건 더 보기 (${shown.length.toLocaleString()} / ${a.length.toLocaleString()}건)</button>`:'';$('#moreBtn')?.addEventListener('click',()=>{visible+=100;render()});$$('.detailBtn').forEach(b=>b.onclick=()=>openDetail(Number(b.dataset.row)));$('#search').parentElement.classList.toggle('hasText',Boolean($('#search').value))}
function openDetail(rowNo){selected=ROWS.find(r=>Number(r[rowNoIndex])===rowNo);if(!selected)return;$('#detailTitle').textContent=val(selected,H.site)||'현장 상세 조회';$('#detailSub').textContent=`${fmt(H.region,val(selected,H.region))} · S/N ${fmt(H.sn,val(selected,H.sn))}`;currentTab='basic';$$('#detailTabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab==='basic'));renderDetail();$('#detailDialog').showModal()}
const groupFields={basic:['S/N','보고서 등급','점검표 매수','현장명','계약명 (명칭 변경 전)','연면적(m2)','세대수','사용승인일','점검 단계','계약 점검(회) > 성능 > 계약(회)','계약 점검(회) > 성능 > 진행(회)','계약 점검(회) > 유지 > 계약(회)','계약 점검(회) > 유지 > 진행(회)','계약 점검(회) > 유지 > 유지관리자 선임','계약 점검(회) > 유지 > 월','지역','계약만료일','법인 구분','점검 구분 (유지) : 업무지원','계약 > 시작','계약 > 종료','분류번호','보고서 문서번호'],work:['문서작성 > 진행월','문서작성 > 완료월','문서작성 > 제본 요청','문서작성 > 제본 입고','접수일자 > 황화일','접수일자 > 파일','현장점검 계획 > 시작','현장점검 계획 > 종료','현장점검 종료','문서작성 진행 현황 > 보고서 작성 완료','문서작성 진행 현황 > 현황','문서 제출 > 유지관리 매뉴얼(부)','문서 제출 > 계획서(부)','문서 제출 > 현황표(부)','문서 제출 > 점검표(부)','문서 제출 > 보고서(부)','문서 제출 > USB(개)','문서 제출 > PDF e-mail']};
function grid(fields){return `<div class="detailGrid">${fields.filter(h=>idx[h]!==undefined).map(h=>`<div class="detailItem"><span>${esc(h)}</span><b>${esc(fmt(h,val(selected,h)))}</b></div>`).join('')}</div>`}
function qty(prefix){const hs=HEADERS.filter(h=>h.startsWith(prefix+' > '));return `<div class="tableWrap"><table class="qtyTable"><thead><tr><th>설비 항목</th><th>수량</th></tr></thead><tbody>${hs.map(h=>{const v=nval(val(selected,h))??0;return `<tr><td>${esc(h.split(' > ')[1])}</td><td class="${v===0?'zero':''}">${v.toLocaleString('ko-KR')}</td></tr>`}).join('')}</tbody></table></div>`}
function compare(){const m=HEADERS.filter(h=>h.startsWith('유지관리 대상 전체 수량 > ')),t=HEADERS.filter(h=>h.startsWith('성능점검 대상 전체 수량 > ')),f=HEADERS.filter(h=>h.startsWith('성능점검 수량 > '));return `<div class="tableWrap"><table class="qtyTable compareTable"><thead><tr><th>설비</th><th>유지관리 전체</th><th>성능점검 대상</th><th>성능점검 확정</th><th>대상→확정 차이</th></tr></thead><tbody>${f.map((h,i)=>{const mv=nval(val(selected,m[i]))??0,tv=nval(val(selected,t[i]))??0,fv=nval(val(selected,h))??0,d=tv-fv;return `<tr><td>${esc(h.split(' > ')[1])}</td><td>${mv.toLocaleString()}</td><td>${tv.toLocaleString()}</td><td><b>${fv.toLocaleString()}</b></td><td class="${d?'diff':''}">${d.toLocaleString()}</td></tr>`}).join('')}</tbody></table></div>`}
function renderDetail(){if(!selected)return;$('#detailBody').innerHTML=currentTab==='basic'?grid(groupFields.basic):currentTab==='work'?grid(groupFields.work):currentTab==='maint'?qty('유지관리 대상 전체 수량'):currentTab==='target'?qty('성능점검 대상 전체 수량'):currentTab==='final'?qty('성능점검 수량'):compare()}
function openFields(){const candidates=HEADERS.filter(h=>!h.includes('수량 > ')&&h!==H.site);$('#fieldChecks').innerHTML=candidates.map(h=>`<label class="checkitem"><input type="checkbox" value="${esc(h)}" ${displayFields.includes(h)?'checked':''}><span>${esc(h)}</span></label>`).join('');$('#fieldDialog').showModal()}
function saveFields(){displayFields=$$('#fieldChecks input:checked').map(x=>x.value);localStorage.setItem(FIELD_STORE,JSON.stringify(displayFields));$('#fieldDialog').close();visible=100;render();toast('검색 표시 항목을 변경했습니다')}
function toast(s){const t=$('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1500)}
$('#dataStamp').textContent=`${D.generatedAt||''} 기준 · ${Number(D.recordCount||ROWS.length).toLocaleString()}개 현장`;
$('#search').addEventListener('input',()=>{visible=100;render()});$('#clearBtn').onclick=()=>{$('#search').value='';visible=100;render();$('#search').focus()};$$('.pill').forEach(b=>b.onclick=()=>{$$('.pill').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;visible=100;render()});$('#fieldBtn').onclick=openFields;$('#saveFieldsBtn').onclick=saveFields;$('#recommendedBtn').onclick=()=>{$$('#fieldChecks input').forEach(x=>x.checked=RECOMMENDED.includes(x.value))};$('#allFieldsBtn').onclick=()=>{$$('#fieldChecks input').forEach(x=>x.checked=true)};$('#noFieldsBtn').onclick=()=>{$$('#fieldChecks input').forEach(x=>x.checked=false)};$$('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());$$('#detailTabs button').forEach(b=>b.onclick=()=>{$$('#detailTabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentTab=b.dataset.tab;renderDetail()});
let deferredPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true};if('serviceWorker'in navigator&&location.protocol.startsWith('http'))window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
render();})();
