(function(root){'use strict';
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function endpoint(value){if(!String(value||'').trim())return '';const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password||u.search||u.hash)throw Error('보고서 연결 주소는 로그인 정보가 없는 HTTPS 주소로 설정하세요.');return u.href.replace(/\/$/,'')}
function nasWebUrl(value){if(!String(value||'').trim())return '';const u=new URL(value);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)throw Error('ipDISK 주소 형식을 확인하세요.');return u.href}
function mappingValue(value){const folder=String(value.folder||'').trim().replace(/\\/g,'/').replace(/\/$/,'');if(!folder||folder.length>1500||folder.startsWith('/')||folder.includes(':')||folder.split('/').some(p=>!p||p==='.'||p==='..'))throw Error('NAS 기준 폴더 아래의 상대 경로를 입력하세요. 예: 유지관리 및 성능점검/② 학교/상록중학교');const reference_date=String(value.reference_date||'');if(reference_date&&(!/^\d{4}-\d{2}-\d{2}$/.test(reference_date)||Number.isNaN(Date.parse(reference_date))||new Date(reference_date).toISOString().slice(0,10)!==reference_date))throw Error('기준일을 확인하세요.');const preferred_file=String(value.preferred_file||'').trim();if(preferred_file.length>500||/[\\/]/.test(preferred_file))throw Error('파일명에는 폴더 경로를 넣지 마세요.');return {folder,reference_date,preferred_file}}
function mappingKey(config,id){if(!Number.isSafeInteger(Number(id))||Number(id)<=0)throw Error('현장 ID를 확인하세요.');return 'staff-report-mapping-v1:'+String(config.supabaseUrl||'')+':'+Number(id)}
function saveLocal(storage,key,value){const text=JSON.stringify(mappingValue(value));storage.setItem(key,text);if(storage.getItem(key)!==text)throw Error('브라우저 저장 내용을 확인할 수 없습니다.');return JSON.parse(text)}
root.ReportFiles={open,endpoint,nasWebUrl,mappingValue,mappingKey,saveLocal};
function open(ctx){
 const dlg=document.createElement('dialog');dlg.className='reportFilesDialog';
 const example=String(ctx.row.site_name||'').includes('상록중학교');
 dlg.innerHTML=`<div class="dlgHead"><div><h3>현장 보고서</h3><small>${escape(ctx.row.site_name)} · 현장 ID ${Number(ctx.row.source_id)}</small></div><button type="button" data-close>닫기</button></div><p>NAS 원본 파일을 조회합니다. 보고서를 확인하고 PDF 열람 또는 다운로드를 선택하세요.</p><div class="filterRow"><a data-nas hidden target="_blank" rel="noopener noreferrer" referrerpolicy="no-referrer">ipDISK에서 보고서 찾기</a><button type="button" data-refresh class="primary">보고서 다시 조회</button></div><div data-nas-guide hidden></div><p data-status role="status" aria-live="polite"></p><div data-list class="reportFilesList"></div>${ctx.admin?`<details class="reportMapping" open><summary>관리자: 현장 보고서 폴더 연결</summary><p>NAS 기준 폴더 아래에서 현장 폴더를 지정하세요. 진행 단계에 따라 이름이 바뀌는 업무 폴더보다 위쪽 현장 폴더를 연결하면 하위 폴더를 다시 검색합니다.</p><label>현장 폴더의 상대 경로<input data-folder lang="ko" placeholder="예: 유지관리 및 성능점검/② 학교/상록중학교"></label><label>성능 실시기준일 (다른 보고서도 함께 보려면 공란)<input data-date type="date"></label><label>우선 표시할 파일명 (선택)<input data-preferred lang="ko" placeholder="예: 제5권 기계설비 성능점검 보고서-상록중학교(기준일 25.04.18).pdf"></label><button type="button" data-save>이 현장에 폴더 연결 저장</button><small>연결 프로그램이 있으면 해당 프로그램에 저장합니다. 연결 전에는 이 PC·브라우저에만 저장되며 다른 기기와 공유되지 않습니다. NAS 원본은 변경하지 않습니다.</small></details>`:''}`;
 document.body.append(dlg);dlg.showModal();const q=s=>dlg.querySelector(s);let base='',closed=false,busy=false,requests=new Set();
 const status=s=>{q('[data-status]').textContent=s};
 const close=()=>{closed=true;requests.forEach(c=>c.abort());dlg.close();dlg.remove()};q('[data-close]').onclick=close;dlg.oncancel=e=>{e.preventDefault();close()};
 let nas='';try{nas=nasWebUrl(ctx.config.reportNasWebUrl);if(nas){q('[data-nas]').href=nas;q('[data-nas]').hidden=false;q('[data-nas-guide]').hidden=false;q('[data-nas-guide]').innerHTML=`<p>ipDISK 창에서 로그인한 후 현장명 <b>${escape(ctx.row.site_name)}</b>으로 해당 폴더를 찾아 파일을 열람하거나 다운로드하세요. 포털 로그인과 NAS 로그인은 별개입니다.</p>${example?'<p>상록중학교 예시 위치: VOL1 → 유지관리 및 성능점검 → ② 학교 → 상록중학교 → 해당 계약 폴더 → 제본 PDF 저장 폴더 → 제출용. 기준일 25.04.18의 PDF를 확인하세요. 진행 폴더명이 바뀌면 현재 폴더를 선택하세요.</p>':''}<small>서버 화면의 파일 조회·다운로드 지원 여부는 실제 접속 확인이 필요합니다. 자동 현장 폴더 이동은 아직 연결되지 않았습니다.</small>`}}catch(e){status(e.message)}
 try{base=endpoint(ctx.config.reportApiUrl)}catch(e){status(e.message)}
 async function request(route,options={}){
  if(!base)throw Error('보고서 연결 프로그램이 아직 설정되지 않았습니다. 서버 연결 확인 후 활성화할 수 있습니다.');
  const session=await ctx.session();if(!session?.access_token)throw Error('포털 로그인이 필요합니다. 다시 로그인하세요.');
  const controller=new AbortController();requests.add(controller);const timer=setTimeout(()=>controller.abort(),60000);
  try{const r=await fetch(base+'/api/sites/'+Number(ctx.row.source_id)+'/'+route,{...options,headers:{Authorization:'Bearer '+session.access_token,...(options.body?{'Content-Type':'application/json'}:{} )},signal:controller.signal,cache:'no-store',redirect:'error'});
   if(!r.ok){const error=await r.json().catch(()=>({}));throw Error(error.error||'보고서 서버 응답 오류 ('+r.status+')')}return options.binary?await r.blob():await r.json();
  }catch(e){if(e.name==='AbortError')throw Error('조회가 취소되었거나 시간이 초과되었습니다. NAS 연결 상태를 확인하세요.');if(e instanceof TypeError)throw Error('보고서 연결 프로그램에 접속할 수 없습니다. HTTPS 주소와 서버 연결을 확인하세요.');throw e}
  finally{clearTimeout(timer);requests.delete(controller)}
 }
 function lock(value){busy=value;dlg.querySelectorAll('[data-refresh],[data-save],button[data-file-id]').forEach(b=>b.disabled=value)}
 async function fileAction(file,view){if(busy)return;const popup=view?window.open('','_blank'):null;if(view&&!popup){status('팝업을 허용한 뒤 열람을 다시 누르세요.');return}if(popup){popup.opener=null;popup.document.body.textContent='보고서를 불러오는 중입니다.'}lock(true);status('파일을 불러오는 중입니다.');try{
  const blob=await request('files/'+file.id+(view?'?view=1':''),{binary:true});if(closed){if(popup)popup.close();return}
  const url=URL.createObjectURL(blob);if(view){popup.location.replace(url)}else{const a=document.createElement('a');a.href=url;a.download=file.name;document.body.append(a);a.click();a.remove()}setTimeout(()=>URL.revokeObjectURL(url),300000);status(view?'PDF 열람 창을 열었습니다.':'다운로드를 시작했습니다.');
 }catch(e){if(popup)popup.close();if(!closed)status(e.message)}finally{if(!closed)lock(false)}}
 async function refresh(){if(busy)return;lock(true);status('이 현장의 보고서 폴더를 확인하고 있습니다.');q('[data-list]').innerHTML='';try{
  const data=await request('reports');if(closed)return;
  if(!data.connected){status('이 현장에 보고서 폴더가 연결되지 않았습니다. 관리자에게 연결 설정을 요청하세요.');return}
  const files=data.files||[];if(!files.length){status('연결된 폴더에서 조건에 맞는 보고서를 찾지 못했습니다. 폴더 위치와 실시기준일을 확인하세요.');return}
  q('[data-list]').innerHTML=`<table><thead><tr><th>파일명</th><th>현장 폴더 안의 위치</th><th>수정일</th><th>크기</th><th>열람·다운로드</th></tr></thead><tbody>${files.map((f,i)=>`<tr><td>${f.preferred?'<b>우선 표시</b> ':''}${escape(f.name)}</td><td>${escape(f.folder==='.'?'현장 폴더':f.folder)}</td><td>${escape(new Date(f.modified*1000).toLocaleString('ko-KR'))}</td><td>${(Number(f.size)/1024/1024).toFixed(2)} MB</td><td>${f.pdf?`<button type="button" data-file-id="${i}" data-view="1">PDF 열람</button>`:''}<button type="button" data-file-id="${i}">다운로드</button></td></tr>`).join('')}</tbody></table>`;
  q('[data-list]').querySelectorAll('[data-file-id]').forEach(b=>b.onclick=()=>fileAction(files[Number(b.dataset.fileId)],b.dataset.view==='1'));status(`${files.length}개 파일을 찾았습니다. 같은 종류의 파일이 여러 개면 파일명과 위치를 확인해 선택하세요.`);
 }catch(e){if(!closed)status(e.message)}finally{if(!closed)lock(false)}}
 q('[data-refresh]').onclick=refresh;
 if(ctx.admin){q('[data-save]').onclick=async()=>{if(busy)return;lock(true);try{const value=mappingValue({folder:q('[data-folder]').value,reference_date:q('[data-date]').value,preferred_file:q('[data-preferred]').value});if(base){await request('mapping',{method:'PUT',body:JSON.stringify(value)});if(!closed)status('연결 프로그램에 폴더 정보를 저장했습니다. 보고서 다시 조회를 눌러 확인하세요.')}else{try{saveLocal(localStorage,mappingKey(ctx.config,ctx.row.source_id),value)}catch(e){throw Error('이 브라우저에 저장하지 못했습니다. 저장소 허용 설정을 확인하세요. '+e.message)}if(!closed)status('폴더 연결 정보를 이 PC·브라우저에 저장했습니다. 창을 다시 열어도 유지됩니다. 다른 PC·휴대폰에는 공유되지 않습니다. 자동 파일 조회는 연결 프로그램 설정이 필요합니다.')}}catch(e){if(!closed)status(e.message)}finally{if(!closed)lock(false)}};
  if(base)request('mapping').then(data=>{if(closed)return;const m=data.mapping;if(m){q('[data-folder]').value=m.folder||'';q('[data-date]').value=m.reference_date||'';q('[data-preferred]').value=m.preferred_file||''}}).catch(e=>{if(!closed)status(e.message)});
 }
 if(!base){q('[data-refresh]').disabled=true;status('보고서 연결 준비 상태입니다. NAS에 접근 가능한 PC·서버에서 연결 프로그램을 실행하고 HTTPS 주소를 설정해야 실제 파일 조회가 가능합니다.');if(ctx.admin&&example){q('[data-folder]').value='유지관리 및 성능점검/② 학교/상록중학교';q('[data-date]').value='2025-04-18';q('[data-preferred]').value='제5권 기계설비 성능점검 보고서-상록중학교(기준일 25.04.18).pdf';status('보고서 연결 준비 상태입니다. 상록중학교의 예시 설정을 표시했습니다. 해당 등록 건의 기준일과 경로를 확인한 뒤 연결 프로그램 설정 후 저장하세요.')}if(nas)status('ipDISK 연결 주소를 설정했습니다. 위 버튼으로 서버 창을 열어 로그인 후 보고서를 찾으세요. 포털 내부 자동 목록 조회는 연결 프로그램 설정 후 사용할 수 있습니다.');}else refresh();
 if(!base&&ctx.admin){try{const raw=localStorage.getItem(mappingKey(ctx.config,ctx.row.source_id));if(raw){const m=mappingValue(JSON.parse(raw));q('[data-folder]').value=m.folder;q('[data-date]').value=m.reference_date;q('[data-preferred]').value=m.preferred_file;status('이 PC·브라우저에 저장된 폴더 정보를 불러왔습니다. 다른 기기와 공유되지 않습니다. ipDISK 버튼으로 서버를 열 수 있으며 자동 목록 조회는 별도 연결이 필요합니다.')}}catch(e){status('저장된 연결 정보를 불러오지 못했습니다. 경로를 다시 입력해 저장하세요. '+e.message)}}
}

})(window);
